language: rust
sudo: true
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
cache: cargo
env:
  global:
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_BACKTRACE=1
before_cache:
  - cargo prune
before_install: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -
  fi
before_script:
  - |
    (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update &&
    (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      export CARGO_INCREMENTAL=0
      export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=on -Zno-landing-pads"
    fi
  - cargo clean
  - cargo build --verbose $CARGO_OPTIONS
  - cargo test --verbose $CARGO_OPTIONS
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      zip -0 ccov.zip `find . \( -name "xor_distance_exercise*.gc*" \) -print`;
      ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" > lcov.info;
      bash <(curl -s https://codecov.io/bash) -f lcov.info;
    fi
